spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bbrick?serverTimezone=UTC&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    dirver-class-name: com.mysql.jdbc.Driver
